/* Static export for Apache/nginx shared hosting (Bluehost).

   `node tools/build-static.mjs`, or `pnpm build:static`. Produces ./out — upload its
   CONTENTS (not the folder itself) to public_html.

   Why a script and not `STATIC_EXPORT=1 next build` in package.json: that is POSIX shell
   syntax and fails on Windows PowerShell, which is where this repo is developed. Spawning
   next with an explicit env is the one form that works on every platform without pulling
   in cross-env.

   It also writes .htaccess into the output. Next copies public/ verbatim, but a dotfile
   there is easy to lose to an editor, an archive tool or an FTP client that hides it — and
   the one file the deploy cannot do without is a bad candidate for that risk. */

import { spawnSync } from "node:child_process";
import { writeFile, readdir, stat, copyFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "out");

const res = spawnSync("next", ["build"], {
  cwd: ROOT,
  stdio: "inherit",
  shell: true,
  env: { ...process.env, STATIC_EXPORT: "1" },
});
if (res.status !== 0) process.exit(res.status ?? 1);

/* ── Flatten the router's prefetch payloads ──────────────────────────────────────────
   Next's export writes the segment-cache payloads as NESTED DIRECTORIES:

     about-company/__next.!KHNpdGUp/$d$slug/__PAGE__.txt

   but the router asks for the same thing with the separators as DOTS:

     about-company/__next.!KHNpdGUp.$d$slug.__PAGE__.txt

   On `next start` that never shows, because the server resolves both. On a plain file host
   it means every prefetch 404s — one per link in the viewport, so seventeen of them on the
   home page. Nothing breaks (the router falls back to a full document load) but the
   console fills with errors and hovering a nav link costs a wasted round trip.

   Copying rather than renaming: the nested form is what `next start` and any future Node
   host would serve, and duplicating a few KB of text is cheaper than picking one. */
const flattenPrefetch = async (dir) => {
  let made = 0;
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (!e.isDirectory()) continue;
    if (e.name.startsWith("__next.")) {
      const collect = async (d, parts) => {
        for (const f of await readdir(d, { withFileTypes: true })) {
          const fp = path.join(d, f.name);
          if (f.isDirectory()) await collect(fp, [...parts, f.name]);
          else {
            await copyFile(fp, path.join(dir, [...parts, f.name].join(".")));
            made++;
          }
        }
      };
      await collect(p, [e.name]);
    } else {
      made += await flattenPrefetch(p);
    }
  }
  return made;
};
const flattened = await flattenPrefetch(OUT);

/* Two jobs only, and deliberately no rewrite rules: trailingSlash already gives every
   route its own index.html, so Apache resolves /about-company/ on its own.

   1. ErrorDocument — without it a bad URL gets Bluehost's default 404, not the site's.
   2. Cache headers — /_next/static filenames contain a content hash, so they are safe to
      pin for a year. Everything else is revalidated, because index.html must never be
      served stale after a deploy. */
const HTACCESS = `# Generated by tools/build-static.mjs — do not edit here, edit the script.

ErrorDocument 404 /404.html

# Hashed build assets: the filename changes whenever the content does, so these can be
# held indefinitely. Anything else has a stable name and must be revalidated.
<IfModule mod_headers.c>
  <FilesMatch "\\.(js|css|woff2?|ttf|otf|webp|avif|jpg|jpeg|png|gif|svg|ico|mp4|webm)$">
    Header set Cache-Control "public, max-age=31536000, immutable"
  </FilesMatch>
  <FilesMatch "\\.(html|json|txt|xml)$">
    Header set Cache-Control "public, max-age=0, must-revalidate"
  </FilesMatch>
</IfModule>

<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/css text/plain text/xml \\
    application/javascript application/json image/svg+xml
</IfModule>

# Fonts and media served cross-origin from a CDN or subdomain.
<IfModule mod_mime.c>
  AddType font/woff2 .woff2
  AddType image/webp .webp
  AddType video/webm .webm
</IfModule>

Options -Indexes
`;

await writeFile(path.join(OUT, ".htaccess"), HTACCESS);

/* Report what shipped, so a truncated export is visible immediately rather than after an
   upload. A missing interior route here means generateStaticParams did not run. */
const walk = async (dir) => {
  let files = 0;
  let bytes = 0;
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) {
      const r = await walk(p);
      files += r.files;
      bytes += r.bytes;
    } else {
      files++;
      bytes += (await stat(p)).size;
    }
  }
  return { files, bytes };
};

const pages = (await readdir(OUT, { withFileTypes: true }))
  .filter((e) => e.isDirectory() && e.name !== "_next" && e.name !== "assets")
  .map((e) => e.name);
const { files, bytes } = await walk(OUT);

console.log(`\nout/  ${files} files, ${(bytes / 1024 / 1024).toFixed(1)} MB`);
console.log(`routes: / , ${pages.sort().join(" , ")}`);
console.log(`wrote out/.htaccess and ${flattened} flattened prefetch payloads`);
console.log(`\nUpload the CONTENTS of out/ to public_html — including the dotfile.`);
